<?php

/**
 * BaseLexeme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $lexeme_item
 * @property enum $belongs
 * @property integer $repite
 * @property float $percent
 * 
 * @method string  getLexemeItem()  Returns the current record's "lexeme_item" value
 * @method enum    getBelongs()     Returns the current record's "belongs" value
 * @method integer getRepite()      Returns the current record's "repite" value
 * @method float   getPercent()     Returns the current record's "percent" value
 * @method Lexeme  setLexemeItem()  Sets the current record's "lexeme_item" value
 * @method Lexeme  setBelongs()     Sets the current record's "belongs" value
 * @method Lexeme  setRepite()      Sets the current record's "repite" value
 * @method Lexeme  setPercent()     Sets the current record's "percent" value
 * 
 * @package    gepfilter
 * @subpackage model
 * @author     Andrew Semikov
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLexeme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lexeme');
        $this->hasColumn('lexeme_item', 'string', 10, array(
             'type' => 'string',
             'primary' => true,
             'length' => 10,
             ));
        $this->hasColumn('belongs', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'spam',
              1 => 'ham',
             ),
             'primary' => true,
             ));
        $this->hasColumn('repite', 'integer', null, array(
             'type' => 'integer',
             'notnull' => 'on',
             ));
        $this->hasColumn('percent', 'float', null, array(
             'type' => 'float',
             'notnull' => 'on',
             ));


        $this->index('viewer_viewed_index', array(
             'fields' => 
             array(
              0 => 'repite',
             ),
             ));
        $this->option('collation', 'utf8');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}