<?php

/**
 * BaseSpamStatView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $word
 * @property integer $ndoc
 * @property integer $nentry
 * 
 * @method text         getWord()   Returns the current record's "word" value
 * @method integer      getNdoc()   Returns the current record's "ndoc" value
 * @method integer      getNentry() Returns the current record's "nentry" value
 * @method SpamStatView setWord()   Sets the current record's "word" value
 * @method SpamStatView setNdoc()   Sets the current record's "ndoc" value
 * @method SpamStatView setNentry() Sets the current record's "nentry" value
 * 
 * @package    gepfilter
 * @subpackage model
 * @author     Andrew Semikov
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpamStatView extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('spam_stat_view');
        $this->hasColumn('word', 'text', null, array(
             'type' => 'text',
             'primary' => true,
             ));
        $this->hasColumn('ndoc', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nentry', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collation', 'utf8');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}