<?php

/**
 * BaseExample
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $content
 * @property enum $state
 * 
 * @method clob    getContent() Returns the current record's "content" value
 * @method enum    getState()   Returns the current record's "state" value
 * @method Example setContent() Sets the current record's "content" value
 * @method Example setState()   Sets the current record's "state" value
 * 
 * @package    gepfilter
 * @subpackage model
 * @author     Andrew Semikov
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExample extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('example');
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('state', 'enum', null, array(
             'type' => 'enum',
             'notnull' => 'on',
             'values' => 
             array(
              0 => 0,
              1 => 1,
              2 => 'spam',
             ),
             'default' => 1,
             ));

        $this->option('collation', 'utf8');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}