<?php

/**
 * KnowledgeBase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gepfilter
 * @subpackage model
 * @author     Andrew Semikov
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class KnowledgeBase extends BaseKnowledgeBase
{
	
}
