options:
  collation: utf8
  charset: utf8

Example:
  actAs:  
    Timestampable:
      created:
        name: created_at
        type: timestamp
      updated:
        disabled: true 
  columns:
    content:
      type: clob
    state:
      type: enum
      notnull: on
      values:
        - 0
        - 1
        - spam
      default:  1
      
      
      
KnowledgeBase:
  actAs:  
    Timestampable:
      created:
        name: created_at
        type: timestamp
      updated:
        disabled: true 
  columns:
    ngram:
      type: string(10)
      notnull: on
      primary: yes
    belongs:
      type: string(10)
      notnull: on
      primary: yes
    repite:
      type: integer
      notnull: on
    percent:
      type: float
      notnull: on
  indexes:
    viewer_viewed:
      fields: [repite]
      
      
Lexeme:
  actAs:  
    Timestampable:
      created:
        name: created_at
        type: timestamp
      updated:
        name: updated_at
        type: timestamp
  columns:
    lexeme_item:
      type: text
      notnull: on
      primary: yes
    belongs:
      type: enum
      values: [spam, ham]
      notnull: true
      primary: yes
    repite:
      type: integer
      notnull: on
    percent:
      type: float
      notnull: on
  indexes:
    viewer_viewed_index:
      fields: [repite]
      
      
SpamStatView:
  columns:
    word:
      type: text
      primary: yes
    ndoc:
      type: integer
    nentry:
      type: integer
   
   
   
HamStatView:
  columns:
    word:
      type: text
      primary: yes
    ndoc:
      type: integer
    nentry:
      type: integer
      
      
ConcatView:
  columns:
    word1:
      type: text
      primary: yes
    ndoc1:
      type: integer
    nentry1:
      type: integer
    is_spam:
      type: integer(1)
      primary: yes
      

TableConcatView:
  columns:
    word1:
      type: text
      primary: yes
    ndoc1:
      type: integer
    nentry1:
      type: integer
    is_spam:
      type: integer(1)
      primary: yes
  indexes:
    word1_index:
      fields: [word1]
    is_spam_index:
      fields: [is_spam]
